# Planteamiento

Tenemos una cuadricula de 12x12 en la que la que conocemos la ocupación de las columnas y de las filas, pero no la distribución de la ocupación.

El reto consiste en, dada una ocupación dada, encontrar la distribución en la matriz.

Existen restricciones. La superficie esta cubierta con termométros que hay que rellenar, y tiene que hacerse desde el bulbo hacia el final, sin dejar huecos.

Fill the thermometers with mercury, such that the numbers outside the grid indicate how many cells in each row and column are filled. Mercury always starts filling from the base (circular part) of a thermometer, towards the top.

Este es el escenario:

![puzzle 19](img/puzzle_19_small.png)

# V0: Sin termometros.

La versión cero resuelve el problema sin termometros, es decir, considera solamente la ocupacion y no el "rellenado", con lo que ofrecera soluciones que no se ajustan a las normas, pero permitira tener un resolvedor en el que poner despues la restricciones.



In [187]:
import numpy as np


In [107]:
#ctes
N_FILAS = 12 # es cuadrado, asi que uso solo una

In [218]:
target_col = np.array([7,5,7,1,7,3,4,4,7,7,7,4])
target_fil = np.array([6,7,6,1,4,3,6,7,6,7,7,3])

In [222]:
tablero = np.zeros(shape =(N_FILAS,N_FILAS))

In [154]:
def limpiar_tablero():
    return np.zeros(shape = (N_FILAS,N_FILAS))

def setear_n_celdas_random_en_tablero( tab, n_values):
    for x in range(n_values):
        coord = np.random.randint(0,N_FILAS,2)
        tab[coord[0]][[coord[1]]] = 1
        
def chequear_solucion(tab):
    ocu_col = np.sum(tablero, axis= 0)
    ocu_fil = np.sum(tablero, axis = 1)
    error = sum(abs(ocu_col - target_col))+ sum(abs(ocu_fil - target_fil))
    return error    


In [224]:
setear_n_celdas_random_en_tablero(tablero, 0)
chequear_solucion(tablero)

126.0

In [185]:
tablero =limpiar_tablero()
sol = chequear_solucion(tablero)
count = 0
maxIter = 9999
while sol >=50 and count < maxIter:
    count += 1                  
    setear_n_celdas_random_en_tablero(tablero, 3)
    sol = chequear_solucion(tablero)
    if maxIter%100 == 0:
        tablero = limpiar_tablero()

print ('n iteraciones: ',count, 'fitness :', sol)
tablero


n iteraciones:  28 fitness : 48.0


array([[0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0.],
       [1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0.],
       [1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1.],
       [0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0.],
       [1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [217]:
# Burdo, pero para ver que ocurre.
# seteamos celdas de tres en tres, al azar, y buscamos soluciones con un buen fitness
# tiene cada 50 pruebas reseteamos el tablero, son 144 casillas, el azar ya ya seteado 150 casillas...
tablero =limpiar_tablero()
sol = chequear_solucion(tablero)
count = 0
maxIter = 99999
while sol >=30 and count < maxIter:
    count += 1                  
    setear_n_celdas_random_en_tablero(tablero, 3)
    sol = chequear_solucion(tablero)
    if count%75 == 0:
        tablero = limpiar_tablero()

print ('n iteraciones: ',count, 'fitness :', sol)

print ('col:',target_col)
print ('try:',np.sum(tablero, dtype = int, axis= 0))
print ('fil:',target_fil)
print ('try:',np.sum(tablero, dtype = int, axis = 1))
tablero

n iteraciones:  35203 fitness : 28.0
col: [7 5 7 1 7 3 4 4 7 7 7 4]
try: [6 7 5 4 7 5 3 4 5 6 6 6]
fil: [6 7 6 1 4 3 6 7 6 7 7 3]
try: [7 8 6 2 4 4 5 7 5 6 5 5]


array([[0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0.],
       [1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0.],
       [0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1.],
       [1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0.]])

In [197]:

chequear_solucion(tablero)

38.0

In [157]:
tablero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])